// import logoV from './icons/V_Logo.svg';
// import logoNameB from './icons/LogoName.svg';
// import logoNameW from './icons/LogoName_white.svg';

import {
  BadgeCheck,
  Bell,
  ChevronsUpDown,
  CreditCard,
  LogOut,
  Sparkles,
  CircleUserRound,
  RectangleEllipsis,
  AudioWaveform,
  BookOpen,
  Bot,
  Command,
  Frame,
  GalleryVerticalEnd,
  Map,
  PieChart,
  Settings2,
  SquareTerminal,
  Folder,
  Forward,
  MoreHorizontal,
  Trash2,
  LayoutDashboard,
  ReceiptText,
  SquareGanttChart,
  ShoppingBasket,
  Ticket,
  Contact,
  Shield,
  Users,
  GroupIcon,
  ArrowLeft,
  ShieldBan,
  Logs,
  MessageCircleQuestion,
  SquareChartGantt,
  Package,
  TrainTrack,
  Search,
  ChartBarStacked,
  List,
  Loader2,
  AlertTriangle,
  ChevronRight,
  ArrowRight,
  ArrowUp,
  PhoneCall,
  RefreshCcwDot,
  Eye,
  EyeClosed,
  Trash,
  Plus,
  ArrowDown,
  X,
  Menu,
  Phone,
} from 'lucide-react';
import { Box, ShoppingBag, ClipboardList } from 'lucide-react';

// export const LogoIcons = {
//   logoV,
//   logoNameB,
//   logoNameW,
// };

export const Arrows = { ArrowRight, ArrowUp, ArrowDown };

export const Icons = {
  Loader2,
  AlertTriangle,
  ChevronRight,
  PhoneCall,
  RefreshCcwDot,
  Eye,
  EyeClosed,
  Trash,
  Plus,
  Search,
  X,
  Menu,
  Phone,
};

export const ComponentsIcons = {
  Search,

  CircleUserRound,
  BadgeCheck,
  Bell,
  ChevronsUpDown,
  CreditCard,
  LogOut,
  Sparkles,
  RectangleEllipsis,
  AudioWaveform,
  BookOpen,
  Bot,
  Command,
  Frame,
  GalleryVerticalEnd,
  Map,
  PieChart,
  Settings2,
  SquareTerminal,
  MessageCircleQuestion,
  Folder,
  Forward,
  MoreHorizontal,
  Trash2,
  LayoutDashboard,
  ReceiptText,
  ShoppingBasket,
  SquareGanttChart,
  Ticket,
  Contact,
  Box,
  ShoppingBag,
  ClipboardList,
  Shield,
  Users,
  GroupIcon,
  Logs,
  ArrowLeft,
  ShieldBan,
  List,
  SquareChartGantt,
  Package,
  TrainTrack,
  ChartBarStacked,
};
